version: '3.3'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: php_damp
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
    ports:
      - 8000:80

  db:
    container_name: mysql_damp
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - 6033:3306

  phpmyadmin:
    container_name: pma_damp
    image: phpmyadmin:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
