class File:

    """
        * return the data need to create required documents.
    """

    def __init__(self, project_name) -> None:
        """
            * declaring public method __init__()

            * @param self
            * @param project_name -> name of the project

            * @return None
        """

        self.project_name = project_name
        self.string = ""

    def dockerfile(self,
                   image: str = ...) -> str:
        """
            * declaring public method dockerfile()
                - return the data of Dockerfile

            * @param self
            * @param image -> name of the php docker image

            * @return str
        """

        string = self.string

        string += f"# Auto generated by DAMPP.\n# Do not remove.\n\n"
        string += f"FROM {image}\n"
        string += f"RUN apt-get update && apt-get upgrade -y\n"
        string += f"RUN docker-php-ext-install mysqli\n"
        string += f"EXPOSE 80\n"

        return string

    def docker_compose(self,
                       docker_version: str = ...,
                       service_web: str = ...,
                       service_db: str = ...,
                       service_pma: str = ...) -> str:
        """
            * declaring public method docker_compose()
                - return the data of docker-compose.yml

            * @param self
            * @param docker_version -> version of Docker
            * @param service_web    -> details of web service
            * @param service_db     -> details of database service
            * @param service_pma    -> details of phpmyadmin service

            * @return str
        """

        string = self.string

        string += f"# Auto generated by DAMPP.\n# Do not remove.\n"
        string += f"\nversion: '{docker_version}'\n"
        string += f"\nservices:\n"
        string += service_web + service_db + service_pma

        return string

    def index_dot_php(self,
                      pma_port: str = ...) -> str:
        """
            * declaring public method index_dot_php()
                - return the data of index.php  

            * @param self
            * @param pma_port -> phpmyadmin port

            * @return str
        """

        string = "\
                <!DOCTYPE html>\
                <html lang=en>\
                <title>DAMP</title>\
                <meta charset=utf-8>\
                <meta content='width = device-width, initial-scale = 1, shrink-to-fit = no' name=viewport>\
                <style>\
                body {\
                    font-family: Ubuntu, sans-serif\
                }\
                \
                div {\
                    padding: .5rem\
                }\
                \
                a {\
                    text-decoration: none\
                }\
                \
                code {\
                    color: #ff1493;\
                    font-weight: 700\
                }\
                \
                .center {\
                    background-color: #fff;\
                    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);\
                    transition: .3s;\
                    border-radius: 12.5px;\
                    padding: 2rem;\
                    margin: 0;\
                    position: absolute;\
                    top: 50%;\
                    left: 50%;\
                    transform: translate(-50%, -50%);\
                    text-align: center\
                }\
                \
                .center:hover {\
                    box-shadow: 0 8px 16px 0 rgba(0, 0, 0, .2)\
                }\
                \
                .btn {\
                    padding: 10px 35.5px 10px 35.5px;\
                    margin-top: 15px;\
                    color: #fff;\
                    background-color: #dc143c;\
                    border: 0;\
                    border-radius: 30px;\
                    font-size: 2.4vh;\
                    font-weight: 700\
                }\
                \
                .btn:hover {\
                    background-color: #000;\
                    color: #fff;\
                    font-weight: 700\
                }\
                \
                .tracking-in-contract {\
                    -webkit-animation: tracking-in-contract .8s cubic-bezier(.215, .61, .355, 1) both;\
                    animation: tracking-in-contract .8s cubic-bezier(.215, .61, .355, 1) both\
                }\
                \
                @-webkit-keyframes tracking-in-contract {\
                    0% {\
                        letter-spacing: 1em;\
                        opacity: 0\
                    }\
                    40% {\
                        opacity: .6\
                    }\
                    100% {\
                        letter-spacing: normal;\
                        opacity: 1\
                    }\
                }\
                \
                @keframes tracking-in-contract {\
                    0% {\
                        letter-spacing: 1em;\
                        opacity: 0\
                    }\
                    40% {\
                        opacity: .6\
                    }\
                    100% {\
                        letter-spacing: normal;\
                        opacity: 1\
                    }\
                }\
                </style>\
                <div class=center>\
                    <span class=tracking-in-contract>\
                        <a href=https://github.com/s3h4n/dampp.git target=_blank>\
                            <h1 style=color:#dc143c>DAMP</h1>\
                        </a>\
                        <h3>Dockerized Apache MySQL PHP</h3>\
                    </span>\
                    <hr>\
                    <div>\
                        <p>Customize \
                            <code>"+f"{self.project_name}"+"/web/index.php</code> \
                        to see the changes.</p>\
                    </div>\
                    <hr>\
                    <div>\
                        <button class=btn onclick=open_php_my_admin() type=button>PhpMyAdmin</button>\
                    </div>\
                </div>\
                <script defer>\
                const open_php_my_admin = () => {\
                    window.open('http://localhost:"+f"{pma_port}"+"/', '_blank');;\
                };\
                </script>\
                </body>\
                </html>"

        return string
